FROM nikolaik/python-nodejs

ADD . /app
WORKDIR /app

RUN virtualenv /ve
RUN /ve/bin/pip install flask==2.0.3
RUN yarn && yarn run tgver

# See https://pythonspeed.com/articles/docker-connection-refused/ for why --host 0.0.0.0
CMD ["/ve/bin/python", "Python/tgve.py", "--host", "0.0.0.0"]
